version: '2'
services:
  wordpress:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: wpengine-geoip
    restart: always
    depends_on:
      - db
    links:
    - db:mysql
    volumes:
      - ../:/var/www/html/wp-content/plugins/wpengine-geoip
    environment:
      WORDPRESS_DB_PASSWORD: password
  db:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=wordpress
